export const styles = `
.dtm{--dtm-text:var(--dsw-alias-label-primary,#20242c);--dtm-muted:var(--dsw-alias-label-secondary,#69717d);--dtm-border:var(--dsw-alias-border-l2,#e1e5ea);--dtm-bg:var(--dsw-alias-bg-layer-3,#fff);--dtm-accent:var(--dsw-alias-state-business-primary,#4169e1);color:var(--dtm-text);max-width:900px;margin:auto;font-size:14px;line-height:1.55}
.dtm *{box-sizing:border-box}.dtm h2{font-size:23px;font-weight:650;margin:0 0 6px}.dtm p{margin:0}.dtm .muted{color:var(--dtm-muted)}
.dtm .scope{display:inline-block;font-size:12px;margin-top:14px;padding:5px 10px;background:color-mix(in srgb,var(--dtm-accent) 8%,transparent);border-radius:6px}
.dtm .summary{display:flex;gap:22px;margin:24px 0 16px;padding-bottom:17px;border-bottom:1px solid var(--dtm-border);color:var(--dtm-muted);font-size:12px}.dtm .summary strong{font-size:23px;color:var(--dtm-text);margin-right:6px;font-variant-numeric:tabular-nums}
.dtm .toolbar{display:flex;flex-wrap:wrap;gap:9px;margin:0 0 14px}.dtm input,.dtm select,.dtm .button{font:inherit;color:var(--dtm-text);background:var(--dtm-bg);border:1px solid var(--dtm-border);border-radius:7px;padding:8px 11px}.dtm input{min-width:170px;flex:1}.dtm select{max-width:160px}.dtm .button{cursor:pointer}.dtm button:disabled{cursor:default;opacity:.45}.dtm :focus-visible{outline:2px solid var(--dtm-accent);outline-offset:3px}
.dtm .status{font-size:12px;min-height:23px;margin-bottom:8px;color:var(--dtm-muted)}.dtm .notice{font-size:13px;border:1px solid var(--dtm-border);border-radius:8px;padding:12px 14px;margin:10px 0 16px;color:var(--dtm-muted)}.dtm .error{color:var(--dsw-alias-state-error-primary,#c03939);border-color:currentColor}
.dtm .list{border:1px solid var(--dtm-border);border-radius:10px;overflow:hidden}.dtm .row{display:flex;gap:16px;align-items:center;padding:16px 18px;border-bottom:1px solid var(--dtm-border)}.dtm .row:last-child{border-bottom:0}.dtm .tool{flex:1;min-width:0}.dtm .name{display:flex;align-items:center;flex-wrap:wrap;gap:9px}.dtm code{font-size:14px;font-weight:600;overflow-wrap:anywhere}.dtm .badge{font-size:10px;letter-spacing:.03em;color:var(--dtm-muted);border:1px solid var(--dtm-border);padding:1px 6px;border-radius:4px}.dtm .description{font-size:12px;color:var(--dtm-muted);margin-top:4px}.dtm .row-state{font-size:11px;color:var(--dtm-muted);margin-top:5px}.dtm .row-state.blocked{color:var(--dsw-alias-state-warn-primary,#ac7335)}
.dtm .switch-area{display:flex;align-items:center;gap:10px;flex-shrink:0;font-size:12px;color:var(--dtm-muted)}.dtm .switch{border:0;width:38px;height:22px;border-radius:20px;background:var(--dsw-alias-fill-secondary,#b5bbc5);padding:3px;cursor:pointer;transition:background .15s}.dtm .switch[aria-checked=true]{background:var(--dtm-accent)}.dtm .switch-knob{display:block;width:16px;height:16px;border-radius:100%;background:white;box-shadow:0 1px 3px #0002;transition:transform .15s}.dtm .switch[aria-checked=true] .switch-knob{transform:translateX(16px)}
.dtm .empty{padding:34px 16px;text-align:center;color:var(--dtm-muted)}.dtm .footer{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:16px 0 22px}.dtm .help{font-size:12px;color:var(--dtm-muted);border-top:1px solid var(--dtm-border);padding-top:14px}.dtm summary{cursor:pointer}.dtm .help p{margin:10px 0;max-width:75ch}.dtm .tool-details{font-size:11px;color:var(--dtm-muted);margin-top:6px}.dtm .tool-details p{white-space:pre-wrap;overflow-wrap:anywhere;margin-top:8px}
@media(max-width:560px){.dtm .row{padding:14px 12px;gap:8px}.dtm .switch-area>span{display:none}.dtm .scope{font-size:11px}.dtm .toolbar input{flex-basis:100%}.dtm .summary{gap:15px}}
`
